version: '2'
services:
  server:
    build:
      context: .
      args:
        CD_VER: 2
    image: kirasoa/cloudera-boot:2
    ports:
      - "7189:7189"
  bootstrap:
    # stdin_open: true
    # tty: true
    depends_on:
      - server
    command: ["sh", "-c", "wait-for-server && cd-bootstrap-remote"]
    build:
      context: .
      args:
        CD_VER: 2
    image: kirasoa/cloudera-boot:2
    volumes:
      - ${PWD}:/cloudera-boot
    working_dir: /cloudera-boot
    environment:
      SERVER_HOST_N_PORT: server:7189
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
  shell:
    # stdin_open: true
    # tty: true
    command: ["sh", "-c", "portforward && /bin/bash"]
    build:
      context: .
      args:
        CD_VER: 2
    image: kirasoa/cloudera-boot:2
    volumes:
      - ${PWD}:/cloudera-boot
    working_dir: /cloudera-boot
    environment:
      SERVER_HOST_N_PORT: localhost:7189
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
